Debut
Saisir(unite,Unité ? 1=°C 2=°F 3=°K)
Si (|unite| = 1 )
Aller(13)
Aller(6)
Si (|unite| = 2 )
Aller(19)
Aller(9)
Si (|unite| = 3 )
Aller(25)
Fin
//Si (|unite| = 1 )
Saisir(valeur,Entrez la température en °C)
Affecter(CtoF, |valeur|*1,8+32)
Affecter(CtoK, |valeur|+273,15)
Afficher( |valeur| °C =  |CtoF| °F = |CtoK| °K)
Aller(11)
//Si (|unite| = 2 )
Saisir(valeur,Entrez la température en °F)
Affecter(FtoC, ( |valeur| - 32) / 1,8)
Affecter(FtoK,  |FtoC| + 273,15)
Afficher( |valeur| °F =  |FtoC| °C = |FtoK| °K)
Aller(11)
//Si (|unite| = 3 )
Saisir(valeur,Entrez la température en °K)
Affecter(KtoC, |valeur|-273,15)
Affecter(KtoF, ( |KtoC| *1,8 + 32) )
Afficher( |valeur| °K =  |KtoC| °C = |KtoF| °F)
Aller(11)
// fin de si
