Debut
Afficher(Ce programme calcule l'indice IMC)
Afficher(IMC: Indice de Masse Corporelle)
Saisir(poids,Entrez votre poids en Kg. )
Saisir(taille,Entrez votre taille en m. )
Affecter(IMC, |poids| / |taille|^2 )
Si (|IMC| < 18)
Afficher(Votre poids est inférieur à la normale !)
Aller(10)
Si (|IMC| >= 18 and |IMC|< 25 )
Afficher(Votre avez un poids "souhaitable".)
Aller(13)
Si (|IMC| >= 25 and |IMC|< 30 )
Afficher(Votre êtes en surpoids)
Aller(16)
Si (|IMC| >= 30 and |IMC|< 40 )
Afficher(Votre êtes en obésité modérée.)
Aller(19)
Si (|IMC| >= 30 and |IMC|< 40 )
Afficher(Vous êtes e obésité massive ! Il faut consulter)
Aller(22)
Affecter(P18,18*|taille|^2 )
Affecter(P25,25*|taille|^2 )
Affecter(P30,30*|taille|^2 )
Affecter(P40,40*|taille|^2 )
Saisir(analyse,Voulez vous l'analyse complète? 0 = NON 1 = OUI)
Si( |analyse| = 0 )
Aller(35)
Aller(30)
Afficher(Votre poids doit être supérieur à |P18| Kg!)
Afficher(Poids normal: Entre |P18| Kg et |P25| Kg !)
Afficher(Surpoids entre |P25| Kg et |P30| Kg !)
Afficher(Obésité modérée entre |P30| Kg et |P40| Kg !)
Afficher(Obésité massive à partir de |P40| Kg !)
Afficher(Programme conçu par Mr TACK le 7/12/2006)
Afficher(Le programme est terminé)
Fin
